site_name: Challenge Open Data

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

markdown_extensions:
  - attr_list
  - pymdownx.arithmatex:
      generic: true
  - tables

theme:
  name: material
  
nav:
  - Accueil: index.md